<a href="https://colab.research.google.com/github/izzul31/Python-Labs/blob/main/Numpy_for_Vector_and_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction and Resources

The contents of this Numpy guide is mainly resourced from https://jakevdp.github.io/PythonDataScienceHandbook/index.html Chapter 2: Introduction to Numpy

There is also an easier guide that is specific to our course here: https://github.com/rojaAchary/vectors_arrays_matrices/tree/main


In [ ]:
import numpy as np
np.array?

A good tips to learn is to ask for help on the syntax or functions. So use "?" after the line to see the documentation.

The main beginner guide is in their website with examples: https://numpy.org/doc/stable/user/absolute_beginners.html

## Numpy

NumPy is the fundamental package for scientific computing with Python.

Website: https://www.numpy.org
Documentation: https://numpy.org/doc
Mailing list: https://mail.python.org/mailman/listinfo/numpy-discussion
Source code: https://github.com/numpy/numpy
Contributing: https://www.numpy.org/devdocs/dev/index.html
Bug reports: https://github.com/numpy/numpy/issues
Report a security vulnerability: https://tidelift.com/docs/security

It provides:

a powerful N-dimensional array object;
sophisticated (broadcasting) functions;
tools for integrating C/C++ and Fortran code;
useful **linear algebra**, Fourier transform, and random number capabilities

From: https://github.com/numpy/numpy

Numpy must first be imported if you do not have the package installed.
To check the installed packages type

In [ ]:
%pip list

This will be one of the most used command in your Machine Learning development

In [ ]:
import numpy as np


Then you can simply type **np** when you want to call the package. For every Jupyter Notebook, you only need to include and run the import statement once and you can use the imported package for the rest of the same notebook. (ref: https://www.studocu.com/en-au/document/university-of-sydney/statistical-modelling-for-business/python-language-companion-to-introduction-to-applied-linear-algebravectorsmatricesand-least-squares/64115357)

## Three ways to make a row vector
Using list in python

Using Numpy array

Using Numpy matrix

In [ ]:
x1 = [1, 3, 2]
x2 = np.array([1,2,3])
x3 = np.matrix([1, 2, 3])

display(x1)
display(x2)
display(x3)

[1, 3, 2]

array([1, 2, 3])

matrix([[1, 2, 3]])

The above is a row vector.
Now declare a column vector

In [ ]:
x4 = [[1], [3], [2]]
x5 = np.array([[1], [3], [2]] )
x6 = np.matrix([[1], [3], [2]] )

display(x4)
display(x5)
display(x6)

[[1], [3], [2]]

array([[1],
       [3],
       [2]])

matrix([[1],
        [3],
        [2]])

## Creating a matrix and making sub-matrices

Let's create a matrix A (4 by 4) and create sub-metrices from A.

In [ ]:
# Define a 4x4 matrix
A = np.array([[1,3,2],[5,6,7],[8,3,1],[4,3,7]])

# Remember that indexing starts at 0 to n-1

A1 = A[1,2]  # this gives the 2nd row, 3rd column value
A2 = A[1,:]  # access the entire 2nd row
A3 = A[:,2]  # access the entire 3rd column

xp = A[1,0:2]

display(A)
display(A1)
display(A2)
display(A3)

array([[1, 3, 2],
       [5, 6, 7],
       [8, 3, 1],
       [4, 3, 7]])

7

array([5, 6, 7])

array([2, 7, 1, 7])

In [ ]:
# More complicated 4x4 matrix
B = np.array([[1,7,9,2],[2,3,3,4],[5,0,2,6],[6,1,5,5]])

B1 = B[1:3,1] #  extract 2nd and 3rd row of column 2
B2 = B[3,1:]  #  extract 2nd through last column of row 4

B3 = B[:-1,1:4]  # extract matrix of 2nd-4th columns and first to next to last rows

B4 = ( B[0,1:4], B[0:3,2].T ) # extract 2nd-4th column of first row and put it on top of 3rd column, 1st-3rd row transposed

display(B)
display(B1)
display(B2)
display(B3)
display(B4)

array([[1, 7, 9, 2],
       [2, 3, 3, 4],
       [5, 0, 2, 6],
       [6, 1, 5, 5]])

array([3, 0])

array([1, 5, 5])

array([[7, 9, 2],
       [3, 3, 4],
       [0, 2, 6]])

(array([7, 9, 2]), array([9, 3, 2]))

## Creating different types of metrices

Zeros Matrix

In [ ]:
zeros_matrix = np.zeros((4, 4))
print(zeros_matrix)

Identity Matrix

In [ ]:
identity_matrix = np.identity(4)
print(identity_matrix)

Create Random Matrix:

containing Integers and Random Numbers, determining it's size.

In [ ]:
randomint_matrix = np.random.randint(10, size=(5, 5))

random_matrix = np.random.rand(10, size=(4, 4))

## Matrix Operations: Transpose, ...

To transpose a matrix the ".T" is used

In [ ]:
C = np.random.randint(10, size=(4, 4))  # Two-dimensional array/matrix size 4 by 4

C1 = C.T  # transpose

display(C)
display(C1)

array([[3, 7, 3, 6],
       [8, 7, 5, 7],
       [3, 8, 7, 2],
       [6, 1, 8, 3]])

array([[3, 8, 3, 6],
       [7, 7, 8, 1],
       [3, 5, 7, 8],
       [6, 7, 2, 3]])


To add matrices the "+" is used

In [ ]:
D = C+B  # transpose

display(C)
display(B)
display(D)

array([[3, 7, 3, 6],
       [8, 7, 5, 7],
       [3, 8, 7, 2],
       [6, 1, 8, 3]])

array([[1, 7, 9, 2],
       [2, 3, 3, 4],
       [5, 0, 2, 6],
       [6, 1, 5, 5]])

array([[ 4, 14, 12,  8],
       [10, 10,  8, 11],
       [ 8,  8,  9,  8],
       [12,  2, 13,  8]])

To multiply matrices the "*" is used

In [ ]:
E = C*B  # transpose

display(C)
display(B)
display(E)

array([[3, 7, 3, 6],
       [8, 7, 5, 7],
       [3, 8, 7, 2],
       [6, 1, 8, 3]])

array([[1, 7, 9, 2],
       [2, 3, 3, 4],
       [5, 0, 2, 6],
       [6, 1, 5, 5]])

array([[ 3, 49, 27, 12],
       [16, 21, 15, 28],
       [15,  0, 14, 12],
       [36,  1, 40, 15]])

To look into the elements you can

In [ ]:
Dlarge = [(D>10)]

display(Dlarge)

[array([[False,  True,  True, False],
        [False, False, False,  True],
        [False, False, False, False],
        [ True, False,  True, False]])]

In [ ]:
# prompt: count the number of true in Dlarge

import numpy as np
count = np.sum(Dlarge[0])
print(count)


5
